const EVENT_TYPE_RESOLUTION_CHANGE = 0;
const EVENT_TYPE_RESOLUTION_TOUCH_MOVE = 1;
const EVENT_TYPE_RESOLUTION_TOUCH_TAP = 2;
const EVENT_TYPE_RESOLUTION_JOYSTICK_CHANGE = 3;
const EVENT_TYPE_RESOLUTION_PAD_BUTTON_TAP = 4;
const EVENT_TYPE_RESOLUTION_GYROSCOPE_CHANGE = 5;
const EVENT_TYPE_SHARE_MEDIA_DATA = 6;
const EVENT_TYPE_MOVE_DATA = 7;

